### ISSUE TITLE
Incorrect error message when pypi url is malformed

### ISSUE THREAD

**Issue by bj00rn** [ewjoachim/sphinx-github-changelog#104]
Seems to be a typo here. Must have been copied from github url check

https://github.com/ewjoachim/sphinx-github-changelog/blob/f623bda5fecae719ec3bb6db9b04b4ae1ab3bdff/sphinx_github_changelog/changelog.py#L96

**Comment by ewjoachim** [comment]
Ah right. Do you want to do a PR to fix that ?

**Comment by bj00rn** [comment]
> Along with the line you mentioned, the person who tackles this PR will want to edit those lines in the tests: https://github.com/ewjoachim/sphinx-github-changelog/blob/main/tests/unit/test_changelog.py#L114 https://github.com/ewjoachim/sphinx-github-changelog/blob/main/tests/unit/test_changelog.py#L126
> 
> Use the ["match" argument](https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest.raises) to match key words in the error message

I'll give it a go. IMHO probably better to subclass ChanglogError but i guess it's a matter of preference

**Comment by ewjoachim** [comment]
Released in https://pypi.org/project/sphinx-github-changelog/1.2.1/

**Comment by ewjoachim** [comment]
> IMHO probably better to subclass ChangelogError but i guess it's a matter of preference here

both would work, but then in simple cases like this, you'd end up having lots of subclasses... It's not as if anyone would be excepting ether type :) Keep it simple, etc.
