### ISSUE TITLE
How to transfer sphinx_github_changelog_token  to display on Read The Docs?

### ISSUE THREAD

**Issue by MiSTeR1995** [ewjoachim/sphinx-github-changelog#106]
Hi!
I don’t quite understand how to make the documentation assembly display releases from github. 
If you create an assembly locally, then everything is displayed, and when I start to assemble on Read the docs, it writes this error Changelog was not built because sphinx_github_changelog_token parameter is missing in the documentation configuration.. Although I pass the token with the rights to read the repository, and my repository is public

**Comment by ewjoachim** [comment]
From the Readme, it says:
```
# Provide a GitHub API token:
# Pass the SPHINX_GITHUB_CHANGELOG_TOKEN environment variable to your build
# OR
sphinx_github_changelog_token = "..."
```
what solution did you chose ?
If you chose the first one, I assume you set the token in the RTD configuration, as shown in the screenshot below ?
![image](https://user-images.githubusercontent.com/1457576/222701847-71031dd6-68f7-4b9f-91e4-e553c1e7486b.png)

If you chose the 2nd one: either you set `sphinx_github_changelog_token = os.environ.get("SOMETHING")`, in which case you need to pass the token as "SOMETHING" in Read The Docs, or you apply a different solution, in which case you're responsible for securing your token.

(I'm assuming that you didn't committed your github token in cleartext to a public repo)

So which one is it ?

**Comment by ewjoachim** [comment]
Ah, one possibility is that you DID commit your token publicly, but GitHub detected it and immediately deactivated the token.

**Comment by MiSTeR1995** [comment]
> Ah, one possibility is that you DID commit your token publicly, but GitHub detected it and immediately deactivated the token.

no, I passed the token through environment variables inside the system and everything worked fine locally. But when I submitted it to the github, the file seemed to have a variable associated with local variable environments, and I think that's why the read the docs simply could not get this token. I will try your second option, it might work

**Comment by MiSTeR1995** [comment]
Thank you very much! The second option helped me display releases directly after commits in github. Topic closed :)

**Comment by ewjoachim** [comment]
> no, I passed the token through environment variables inside the system and everything worked fine locally. But when I submitted it to the github, the file seemed to have a variable associated with local variable environments, and I think that's why the read the docs simply could not get this token. I will try your second option, it might work

Frankly, I don't have the slightest idea what you're talking about, but I'm glad it turned out how you wanted. Cheers.
