### ISSUE TITLE
Environment variable returns None

### ISSUE THREAD

**Issue by sahiljhawar** [ewjoachim/sphinx-github-changelog#123]
I added the environment variable to the repo however while deploying the pages, the following error occurs.

```bash
Exception occurred:
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sphinx_github_changelog/changelog.py", line 44, in compute_changelog
    return no_token(changelog_url=options["changelog-url"])
KeyError: 'changelog-url'
```

**Comment by sahiljhawar** [comment]
I am using the variable inside `conf.py`

`sphinx_github_changelog_token = os.getenv("SPHINX_GITHUB_CHANGELOG_TOKEN")
`

When I set the same secret on my local machine, everything worked fine but on the production docs it is not working.

**Comment by sahiljhawar** [comment]
on the documentation website the following appears:

> **Warning**
> Changelog was not built because sphinx_github_changelog_token parameter is missing in the documentation configuration.

**Comment by sahiljhawar** [comment]
and when I add the change-log url it refers to same page:

https://nuclear-multimessenger-astronomy.github.io/nmma/changelog.html

**Comment by sahiljhawar** [comment]
Found the solution for this:

Refer here: https://github.com/nuclear-multimessenger-astronomy/nmma/blob/089e1b6bcd53078a263585b96612b4ea44c2d7eb/.github/workflows/deploy-github-pages.yml#L41C1-L47C1

**Comment by ewjoachim** [comment]
Yes, the environment variable needs to be set at the step where the doc is built, otherwise it's not found when building.

That said, the error should look nicer.

**Comment by ewjoachim** [comment]
> `sphinx_github_changelog_token = os.getenv("SPHINX_GITHUB_CHANGELOG_TOKEN") `

This is not useful, the value of the token is by default the value of the `SPHINX_GITHUB_CHANGELOG_TOKEN`, per [documentation](https://github.com/ewjoachim/sphinx-github-changelog?tab=readme-ov-file#extension-options-confpy). You can remove this line from conf.py, it should still work.

**Comment by ewjoachim** [comment]
> That said, the error should look nicer.

Turns out it was a bug due to the lib not handling correctly the case where there's no token and no changelog-url. Fixed in #124.

**Comment by sahiljhawar** [comment]
Thanks, I realised I was not using variable at the correct place in the yml. This is mainly due to my novice knowledge in CI/CD.

**Comment by ewjoachim** [comment]
Yeah, but your report led to fixing a real bug in the lib, so congratulations :)
