### ISSUE TITLE
Consider adding support of GitHub Enterprise self-hosted Server

### ISSUE THREAD

**Issue by dzuev2** [ewjoachim/sphinx-github-changelog#138]
Currently sphinx-github-changelog extension assumes that repo/release notes are hosted on a public github.com platform:

https://github.com/ewjoachim/sphinx-github-changelog/blob/16940159da1fae7cf09c0b78436acf9be10512f3/sphinx_github_changelog/changelog.py#L75-L85

https://github.com/ewjoachim/sphinx-github-changelog/blob/16940159da1fae7cf09c0b78436acf9be10512f3/sphinx_github_changelog/changelog.py#L164C12-L164C42

Our organization runs self hosted github enterprise server: https://docs.github.com/en/enterprise-server@3.10/admin/overview/about-github-enterprise-server and would like to utilize this extension to generate sphinx docs. I believe the change should be pretty trivial:

- relax valid url check
- add env variable to override graphql api path, default to "https://api.github.com/graphql"

**Comment by ewjoachim** [comment]
Hello, thanks for your suggestion. I have limited time these days for engaging with improvements on this lib, but if you want to do a PR, I'll be happy to have a look :)

**Comment by dzuev2** [comment]
I have a change ready in my local repo, however it seems like I do not have write access to propose a PR:

```
Creating branch dzuev2/support_self_hosted_repo
Switched to a new branch 'dzuev2/support_self_hosted_repo'
remote: Permission to ewjoachim/sphinx-github-changelog.git denied to dzuev2.
fatal: unable to access 'https://github.com/ewjoachim/sphinx-github-changelog.git/': The requested URL returned error: 403
remote: Permission to ewjoachim/sphinx-github-changelog.git denied to dzuev2.
fatal: unable to access 'https://github.com/ewjoachim/sphinx-github-changelog.git/': The requested URL returned error: 403
Finished creating branch dzuev2/support_self_hosted_repo
```

Could you please grant the perms?

**Comment by ewjoachim** [comment]
Oh, it looks like it's the first time you're doing a PR in an open source context, congratulations then :) The process is a bit different from a repo you own (or on which you have permissions):

- Fork the repo (from [the repo main page](https://github.com/ewjoachim/sphinx-github-changelog/))
<img width="154" alt="Screenshot 2024-08-08 at 22 01 05" src="https://github.com/user-attachments/assets/d99be2f7-8202-476f-9b58-4fa7f552cddf">

- Configure the 2 remotes locally in `git`: you're used to work with `origin` which currently points to `ewjoachim/sphinx-github-changelog`. The standard with forks is that `origin` would be your fork instead, and the upstream repo (my repo) would be `upstream`:

```console
$ # Rename the current "origin" remote as "upstream
$ git remote rename origin upstream
$ # Create a new remote named "origin" pointing to your fork
$ git remote add origin https://github.com/dzuev2/sphinx-github-changelog.git
```

- Push the branch `dzuev2/support_self_hosted_repo` (note that you don't have to prefix the branch name with `dzuev2`, it will be in your fork only, so no risk of mixing up) to your fork (which belongs to you so you have the necessary permissions by definition

```console
$ # We've made it so that origin is your fork, so you can push to origin as usual
$ git push origin dzuev2/support_self_hosted_repo
```

- Open a PR **from** `support_self_hosted_repo` in your fork **to** `main` in this repo (`ewjoachim`). Note that this should be the default destination GitHub will suggest when you create a PR for your branch.

- In the future, if you want to contribute again, and you still have your fork around, you can pull from `upstream`:

```console
$ # get to your local main branch
$ git checkout main
$ # pull commits from upstream's main (ff-only is to make sure that you didn't have commits in your local main that didn't come from distant main)
$ git pull --ff-only upstream main
```

Happy contributing :)
