### ISSUE TITLE
Conda Package

### ISSUE THREAD

**Issue by curtisma** [ewjoachim/sphinx-github-changelog#57]
Many people use conda instead of pip to create Python virtual environments.  
Many Sphinx projects already have Conda package.  It would make it much easier to install this using Conda if a Conda recipe was contributed at [conda-forge](https://conda-forge.org/) by following the [contribution instructions](https://conda-forge.org/#add_recipe).

**Comment by ewjoachim** [comment]
Hello !
I'm not a conda user so while I'm ok doing a package, I won't be the best person to test it or make sure it keeps working. Do you want to be the contact for conda-related issues in the future ?

**Comment by curtisma** [comment]
Yeah

**Comment by ewjoachim** [comment]
The rest will happen there: https://github.com/pulls?q=is%3Apr+is%3Aopen+author%3A%40me+archived%3Afalse+sort%3Aupdated-desc

**Comment by ewjoachim** [comment]
Shall we close ?

**Comment by curtisma** [comment]
> Shall we close ?

Sounds good.  👍
